<?php

namespace App\Models\Concerns;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

/**
 * UUID primary keys, generated as UUIDv7 (DATABASE.md §0.2).
 *
 * UUIDv7 is globally unique and time-ordered, so index leaf splits and
 * page-cache churn stay low on high-volume tables — without the
 * enumerability of a sequence. IDs are always generated by the application
 * at insert time; there are no database sequences in Swasthya.
 *
 * Every domain model uses this trait. Properties are expressed as method
 * overrides (getIncrementing/getKeyType) so the trait never collides with
 * the parent Model's property declarations.
 */
trait HasUuid
{
    public function getIncrementing(): bool
    {
        return false;
    }

    public function getKeyType(): string
    {
        return 'string';
    }

    public static function bootHasUuid(): void
    {
        static::creating(function (Model $model): void {
            if (empty($model->getAttribute($model->getKeyName()))) {
                $model->setAttribute($model->getKeyName(), Str::uuid7()->toString());
            }
        });
    }
}
