<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Identity foundation: the global users table (DATABASE.md §3.4).
 *
 * `users` is deliberately the ONE global identity table — it carries no
 * tenant_id. An account is a person's identity, not a tenant's record;
 * tenancy is expressed through role_assignments (user × role × tenant ×
 * scope) when the tenancy phase lands (DATABASE.md §1.3).
 *
 * Conventions exercised here (DATABASE.md §0):
 *  - UUID primary key, generated by the application (UUIDv7) — no sequences;
 *  - timestamptz everywhere, maintained by the ORM;
 *  - status as text + CHECK constraint (evolvable, §0.5);
 *  - case-insensitive unique email via a lower(email) index;
 *  - soft delete as status lifecycle (deleted_at), never hard DELETE.
 *
 * This table is the identity foundation ONLY — authentication, MFA, tokens,
 * and role assignments arrive with Phases 3–4.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('users', function (Blueprint $table): void {
            $table->uuid('id')->primary();
            $table->string('email', 255);
            $table->text('password_hash');
            $table->text('status')->default('pending');
            $table->timestampTz('last_login_at')->nullable();
            $table->timestampTz('password_changed_at')->nullable();
            $table->timestampsTz();
            $table->softDeletesTz();
        });

        // Status is a text + CHECK state machine, not a native enum —
        // evolvable, introspectable, and guarded in the database
        // (DATABASE.md §0.5).
        DB::statement(
            "alter table users add constraint chk_users_status check (status in ('pending', 'active', 'locked', 'disabled'))"
        );

        // Case-insensitive uniqueness (DATABASE.md §3.4: email unique
        // case-insensitively). Named per the §0.1 convention (uq_<table>_<cols>).
        DB::statement('create unique index uq_users_email_lower on users (lower(email))');
    }

    public function down(): void
    {
        Schema::dropIfExists('users');
    }
};
