<?php

namespace Database\Seeders;

use App\Models\Module;
use Illuminate\Database\Seeder;

class ModuleSeeder extends Seeder
{
    public function run(): void
    {
        $modules = [
            // ── Core modules (always enabled) ─────────────────────────
            [
                'code' => 'patients',
                'name' => 'Patient Management',
                'description' => 'Patient registration, demographics, medical history, and record management',
                'domain' => 'patient',
                'category' => 'core',
                'is_core' => true,
                'dependencies' => [],
                'required_permissions' => [],
                'sort_order' => 1,
                'nav_config' => ['icon' => 'Users', 'group' => 'clinical'],
            ],
            [
                'code' => 'appointments',
                'name' => 'Appointments & Scheduling',
                'description' => 'Appointment booking, scheduling, queue management, and check-in',
                'domain' => 'appointment',
                'category' => 'core',
                'is_core' => true,
                'dependencies' => ['patients'],
                'required_permissions' => [],
                'sort_order' => 2,
                'nav_config' => ['icon' => 'CalendarDays', 'group' => 'clinical'],
            ],
            [
                'code' => 'encounters',
                'name' => 'Clinical Encounters',
                'description' => 'OPD consultations, clinical documentation, notes, and sign-off',
                'domain' => 'encounter',
                'category' => 'core',
                'is_core' => true,
                'dependencies' => ['patients', 'appointments'],
                'required_permissions' => [],
                'sort_order' => 3,
                'nav_config' => ['icon' => 'Stethoscope', 'group' => 'clinical'],
            ],

            // ── Clinical modules ──────────────────────────────────────
            [
                'code' => 'pharmacy',
                'name' => 'Pharmacy',
                'description' => 'Prescription dispensing, medication management, and pharmacy inventory',
                'domain' => 'pharmacy',
                'category' => 'clinical',
                'is_core' => false,
                'dependencies' => ['patients', 'encounters'],
                'required_permissions' => ['pharmacy.view', 'pharmacy.dispense'],
                'sort_order' => 10,
                'nav_config' => ['icon' => 'Pill', 'group' => 'operations'],
            ],
            [
                'code' => 'laboratory',
                'name' => 'Laboratory',
                'description' => 'Lab orders, specimen handling, result entry, verification, and reporting',
                'domain' => 'lab',
                'category' => 'clinical',
                'is_core' => false,
                'dependencies' => ['patients', 'encounters'],
                'required_permissions' => ['laboratory.view', 'laboratory.orders'],
                'sort_order' => 11,
                'nav_config' => ['icon' => 'TestTube', 'group' => 'clinical'],
            ],
            [
                'code' => 'radiology',
                'name' => 'Radiology',
                'description' => 'Imaging orders, study management, reporting, and modality worklist',
                'domain' => 'radiology',
                'category' => 'clinical',
                'is_core' => false,
                'dependencies' => ['patients', 'encounters'],
                'required_permissions' => ['radiology.view', 'radiology.orders'],
                'sort_order' => 12,
                'nav_config' => ['icon' => 'ScanLine', 'group' => 'clinical'],
            ],
            [
                'code' => 'ipd',
                'name' => 'Inpatient Department',
                'description' => 'Admissions, bed management, transfers, discharge, and nursing documentation',
                'domain' => 'admission',
                'category' => 'clinical',
                'is_core' => false,
                'dependencies' => ['patients', 'encounters'],
                'required_permissions' => ['ipd.view', 'ipd.admit'],
                'sort_order' => 13,
                'nav_config' => ['icon' => 'BedDouble', 'group' => 'clinical'],
            ],
            [
                'code' => 'emergency',
                'name' => 'Emergency Department',
                'description' => 'ER registration, triage, time-stamped events, and disposition',
                'domain' => 'er',
                'category' => 'clinical',
                'is_core' => false,
                'dependencies' => ['patients'],
                'required_permissions' => ['emergency.view', 'emergency.triage'],
                'sort_order' => 14,
                'nav_config' => ['icon' => 'Siren', 'group' => 'clinical'],
            ],
            [
                'code' => 'ot',
                'name' => 'Operating Theatre',
                'description' => 'Surgical scheduling, procedure documentation, safety checklists',
                'domain' => 'ot',
                'category' => 'clinical',
                'is_core' => false,
                'dependencies' => ['patients', 'ipd'],
                'required_permissions' => ['ot.view', 'ot.schedule'],
                'sort_order' => 15,
                'nav_config' => ['icon' => 'Scissors', 'group' => 'clinical'],
            ],
            [
                'code' => 'icu',
                'name' => 'Intensive Care Unit',
                'description' => 'ICU admissions, observations, critical-care documentation, and step-down',
                'domain' => 'icu',
                'category' => 'clinical',
                'is_core' => false,
                'dependencies' => ['patients', 'ipd'],
                'required_permissions' => ['icu.view', 'icu.document'],
                'sort_order' => 16,
                'nav_config' => ['icon' => 'HeartPulse', 'group' => 'clinical'],
            ],
            [
                'code' => 'bloodbank',
                'name' => 'Blood Bank',
                'description' => 'Donor management, blood processing, crossmatching, transfusion, and discard',
                'domain' => 'bloodbank',
                'category' => 'clinical',
                'is_core' => false,
                'dependencies' => ['patients'],
                'required_permissions' => ['bloodbank.view', 'bloodbank.process'],
                'sort_order' => 17,
                'nav_config' => ['icon' => 'Droplets', 'group' => 'clinical'],
            ],
            [
                'code' => 'oncology',
                'name' => 'Oncology',
                'description' => 'Cancer treatment plans, chemotherapy protocols, and radiotherapy',
                'domain' => 'oncology',
                'category' => 'clinical',
                'is_core' => false,
                'dependencies' => ['patients', 'encounters', 'pharmacy'],
                'required_permissions' => ['oncology.view', 'oncology.treat'],
                'sort_order' => 18,
                'nav_config' => ['icon' => 'Crosshair', 'group' => 'clinical'],
            ],
            [
                'code' => 'telehealth',
                'name' => 'Telehealth',
                'description' => 'Virtual consultations, video sessions, and remote follow-up',
                'domain' => 'telehealth',
                'category' => 'clinical',
                'is_core' => false,
                'dependencies' => ['patients', 'appointments'],
                'required_permissions' => ['telehealth.view', 'telehealth.session'],
                'sort_order' => 19,
                'nav_config' => ['icon' => 'Video', 'group' => 'clinical'],
            ],
            [
                'code' => 'rpm',
                'name' => 'Remote Patient Monitoring',
                'description' => 'Device enrollment, vital sign tracking, alerts, and escalation',
                'domain' => 'rpm',
                'category' => 'clinical',
                'is_core' => false,
                'dependencies' => ['patients'],
                'required_permissions' => ['rpm.view', 'rpm.monitor'],
                'sort_order' => 20,
                'nav_config' => ['icon' => 'Activity', 'group' => 'clinical'],
            ],

            // ── Operations modules ────────────────────────────────────
            [
                'code' => 'inventory',
                'name' => 'Inventory Management',
                'description' => 'Stock tracking, transfers, adjustments, and batch management',
                'domain' => 'inventory',
                'category' => 'operations',
                'is_core' => false,
                'dependencies' => [],
                'required_permissions' => ['inventory.view', 'inventory.manage'],
                'sort_order' => 30,
                'nav_config' => ['icon' => 'Boxes', 'group' => 'operations'],
            ],
            [
                'code' => 'procurement',
                'name' => 'Procurement',
                'description' => 'Purchase requests, orders, receiving, three-way match, and vendor management',
                'domain' => 'procurement',
                'category' => 'operations',
                'is_core' => false,
                'dependencies' => ['inventory'],
                'required_permissions' => ['procurement.view', 'procurement.manage'],
                'sort_order' => 31,
                'nav_config' => ['icon' => 'ShoppingCart', 'group' => 'operations'],
            ],

            // ── Finance modules ───────────────────────────────────────
            [
                'code' => 'billing',
                'name' => 'Billing & Invoicing',
                'description' => 'Charge capture, invoices, payments, refunds, and revenue cycle management',
                'domain' => 'billing',
                'category' => 'finance',
                'is_core' => false,
                'dependencies' => ['patients'],
                'required_permissions' => ['billing.view', 'billing.manage'],
                'sort_order' => 40,
                'nav_config' => ['icon' => 'Receipt', 'group' => 'finance'],
            ],
            [
                'code' => 'finance',
                'name' => 'Financial Management',
                'description' => 'Budgets, expenses, financial periods, and accounting integration',
                'domain' => 'finance',
                'category' => 'finance',
                'is_core' => false,
                'dependencies' => ['billing'],
                'required_permissions' => ['finance.view', 'finance.manage'],
                'sort_order' => 41,
                'nav_config' => ['icon' => 'WalletCards', 'group' => 'finance'],
            ],

            // ── Administration modules ────────────────────────────────
            [
                'code' => 'hr',
                'name' => 'Human Resources',
                'description' => 'Staff management, scheduling, attendance, and payroll configuration',
                'domain' => 'hr',
                'category' => 'admin',
                'is_core' => false,
                'dependencies' => [],
                'required_permissions' => ['hr.view', 'hr.manage'],
                'sort_order' => 50,
                'nav_config' => ['icon' => 'UserCog', 'group' => 'admin'],
            ],
            [
                'code' => 'analytics',
                'name' => 'Analytics & Reporting',
                'description' => 'Operational dashboards, clinical reports, and compliance reporting',
                'domain' => 'analytics',
                'category' => 'admin',
                'is_core' => false,
                'dependencies' => [],
                'required_permissions' => ['analytics.view'],
                'sort_order' => 51,
                'nav_config' => ['icon' => 'ChartNoAxesCombined', 'group' => 'admin'],
            ],
            [
                'code' => 'notifications',
                'name' => 'Notifications & Messaging',
                'description' => 'In-app notifications, alerts, email/SMS integration, and emergency broadcasts',
                'domain' => 'notifications',
                'category' => 'admin',
                'is_core' => false,
                'dependencies' => [],
                'required_permissions' => ['notifications.manage'],
                'sort_order' => 52,
                'nav_config' => ['icon' => 'Bell', 'group' => 'admin'],
            ],
            [
                'code' => 'portal',
                'name' => 'Patient Portal',
                'description' => 'Patient-facing portal for appointments, records, messaging, and self-service',
                'domain' => 'portal',
                'category' => 'admin',
                'is_core' => false,
                'dependencies' => ['patients', 'appointments'],
                'required_permissions' => ['portal.manage'],
                'sort_order' => 53,
                'nav_config' => ['icon' => 'PanelsTopLeft', 'group' => 'admin'],
            ],
            [
                'code' => 'documents',
                'name' => 'Document Management',
                'description' => 'Document upload, indexing, imaging, and secure storage',
                'domain' => 'documents',
                'category' => 'admin',
                'is_core' => false,
                'dependencies' => [],
                'required_permissions' => ['documents.view', 'documents.manage'],
                'sort_order' => 54,
                'nav_config' => ['icon' => 'FileText', 'group' => 'admin'],
            ],
        ];

        foreach ($modules as $moduleData) {
            Module::updateOrCreate(
                ['code' => $moduleData['code']],
                array_merge($moduleData, ['is_active' => true])
            );
        }
    }
}
