<?php

namespace App\Http\Controllers\Api;

use App\Exceptions\ApiException;
use App\Http\Controllers\Controller;
use App\Http\Requests\FollowUp\BookFollowUpRequest;
use App\Http\Requests\FollowUp\CancelFollowUpRequest;
use App\Http\Requests\FollowUp\StoreFollowUpRequest;
use App\Models\Appointment;
use App\Models\Encounter;
use App\Models\FollowUp;
use App\Models\Patient;
use App\Models\Staff;
use App\Support\AccessCheck;
use App\Support\AuditLogger;
use App\Support\Envelope;
use App\Support\ErrorCodes;
use App\Support\TenantContext;
use Illuminate\Database\QueryException;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

/**
 * Follow-up planning (DATABASE.md §3.17, PRODUCT_REQUIREMENTS §6.7): the
 * encounter provider plans a return visit or teleconsult, linked to the
 * encounter; the plan can be linked to a real appointment (booked), marked
 * completed when the visit happens, or cancelled with a reason. Every
 * transition is a compare-and-swap on (status, lock_version).
 */
final class FollowUpController extends Controller
{
    public function __construct(
        private readonly AuditLogger $audit,
    ) {}

    /**
     * POST /encounters/{encounter}/follow-ups — plan a follow-up on an open
     * encounter (the plan is part of the live visit; once signed, the record
     * is final).
     */
    public function create(StoreFollowUpRequest $request, Encounter $encounter): JsonResponse
    {
        AccessCheck::scoped($encounter, write: true);

        if ($encounter->status !== Encounter::STATUS_OPEN) {
            throw new ApiException(
                ErrorCodes::CONFLICT,
                'A follow-up can only be planned on an open encounter (current status: '.$encounter->status.').',
                409,
            );
        }

        $context = TenantContext::current();
        $provider = $this->currentProvider($encounter, $context);

        $providerStaffId = $request->validated('providerStaffId') ?? $provider->getKey();

        if ($providerStaffId !== $provider->getKey()) {
            // A different in-scope active provider may be named, but never
            // one from another tenant or facility.
            $named = Staff::query()
                ->where('tenant_id', $encounter->tenant_id)
                ->where('facility_id', $encounter->facility_id)
                ->where('id', $providerStaffId)
                ->where('status', '!=', Staff::STATUS_DEPARTED)
                ->exists();

            if (! $named) {
                throw new ApiException(ErrorCodes::VALIDATION_ERROR, 'The named provider is not an active staff member in this facility.', 422);
            }
        }

        $followUp = FollowUp::query()->create([
            'tenant_id' => $encounter->tenant_id,
            'facility_id' => $encounter->facility_id,
            'patient_id' => $encounter->patient_id,
            'encounter_id' => $encounter->getKey(),
            'provider_staff_id' => $providerStaffId,
            'follow_up_type' => $request->validated('followUpType'),
            'planned_at' => $request->date('plannedAt'),
            'reason' => $request->validated('reason'),
            'status' => FollowUp::STATUS_PLANNED,
            'lock_version' => 0,
            'created_by' => $context->user?->getKey(),
        ]);

        $this->audit->record(
            'follow_up.planned',
            'follow_up',
            $followUp->getKey(),
            ['patientId' => $followUp->patient_id, 'encounterId' => $followUp->encounter_id, 'followUpType' => $followUp->follow_up_type, 'plannedAt' => $followUp->planned_at?->toIso8601String(), 'providerStaffId' => $followUp->provider_staff_id],
            $request,
        );

        return Envelope::success(data: self::present($followUp), status: 201, request: $request);
    }

    /**
     * GET /encounters/{encounter}/follow-ups — the care team's view of the
     * plans generated by this visit, oldest planned first.
     */
    public function forEncounter(Request $request, Encounter $encounter): JsonResponse
    {
        AccessCheck::scoped($encounter, write: false);

        $followUps = $encounter->followUps()
            ->orderBy('planned_at')
            ->get()
            ->map(fn (FollowUp $followUp): array => self::present($followUp))
            ->values();

        return Envelope::success(data: $followUps, request: $request);
    }

    /**
     * GET /patients/{patient}/follow-ups — the patient's upcoming visits
     * (planned or booked). Scoped to the bound patient; released to the
     * care team with followup:view.
     */
    public function forPatient(Request $request, Patient $patient): JsonResponse
    {
        AccessCheck::scoped($patient, write: false);

        $followUps = FollowUp::query()
            ->where('patient_id', $patient->getKey())
            ->whereIn('status', [FollowUp::STATUS_PLANNED, FollowUp::STATUS_BOOKED])
            ->orderBy('planned_at')
            ->get()
            ->map(fn (FollowUp $followUp): array => self::present($followUp))
            ->values();

        return Envelope::success(data: $followUps, request: $request);
    }

    /**
     * POST /follow-ups/{followUp}/book — link the plan to the real booked
     * appointment (same patient, same facility — verified, never assumed).
     */
    public function book(BookFollowUpRequest $request, FollowUp $followUp): JsonResponse
    {
        AccessCheck::scoped($followUp, write: true);
        $this->guardStatus($followUp, [FollowUp::STATUS_PLANNED], 'booked');

        $appointment = Appointment::query()
            ->where('tenant_id', $followUp->tenant_id)
            ->where('facility_id', $followUp->facility_id)
            ->where('id', $request->validated('appointmentId'))
            ->first();

        if ($appointment === null || $appointment->patient_id !== $followUp->patient_id) {
            throw new ApiException(
                ErrorCodes::VALIDATION_ERROR,
                'The appointment must be for the same patient in the same facility as the follow-up plan.',
                422,
            );
        }

        $context = TenantContext::current();
        $this->applyTransition($followUp, [FollowUp::STATUS_PLANNED], [
            'status' => FollowUp::STATUS_BOOKED,
            'booked_appointment_id' => $appointment->getKey(),
        ], $context);

        $this->audit->record(
            'follow_up.booked',
            'follow_up',
            $followUp->getKey(),
            ['patientId' => $followUp->patient_id, 'encounterId' => $followUp->encounter_id, 'appointmentId' => $appointment->getKey()],
            $request,
        );

        return Envelope::success(data: self::present($followUp->fresh()), request: $request);
    }

    /**
     * POST /follow-ups/{followUp}/auto-book — the plan BECOMES the booking:
     * the appointment is created from the follow-up plan (patient, provider,
     * facility, planned time) and linked to it in one atomic step — no
     * separately-booked appointment needed (PRODUCT_REQUIREMENTS §6.7,
     * DATABASE.md §3.17a). The appointment type follows the plan
     * (return_visit → follow_up, teleconsult → teleconsult); the slot races
     * on the provider-start unique index, so two plans for the same provider
     * and start can never both book.
     */
    public function autoBook(Request $request, FollowUp $followUp): JsonResponse
    {
        AccessCheck::scoped($followUp, write: true);

        $context = TenantContext::current();

        try {
            [$appointment, $followUp] = DB::transaction(function () use ($followUp, $context): array {
                // Lock the plan: concurrent auto-books of the SAME follow-up
                // serialize here — the loser reads status booked and gets a 409.
                $locked = FollowUp::query()
                    ->where('tenant_id', $followUp->tenant_id)
                    ->where('id', $followUp->getKey())
                    ->lockForUpdate()
                    ->first();

                if ($locked === null) {
                    throw new ApiException(ErrorCodes::NOT_FOUND, 'Follow-up not found.', 404);
                }

                $this->guardStatus($locked, [FollowUp::STATUS_PLANNED], 'auto-booked');

                $startsAt = $locked->planned_at;

                $appointment = Appointment::query()->create([
                    'tenant_id' => $locked->tenant_id,
                    'facility_id' => $locked->facility_id,
                    'patient_id' => $locked->patient_id,
                    'provider_staff_id' => $locked->provider_staff_id,
                    'service_id' => null,
                    'appointment_type' => $locked->follow_up_type === FollowUp::TYPE_TELECONSULT
                        ? Appointment::TYPE_TELECONSULT
                        : Appointment::TYPE_FOLLOW_UP,
                    'starts_at' => $startsAt,
                    // The plan carries no duration; the canonical 15-minute
                    // consultation window (the schedule slot default).
                    'ends_at' => $startsAt->copy()->addMinutes(15),
                    'status' => Appointment::STATUS_BOOKED,
                    'source' => Appointment::SOURCE_FOLLOW_UP,
                    'lock_version' => 0,
                    'created_by' => $context->user?->getKey(),
                ]);

                $this->applyTransition($locked, [FollowUp::STATUS_PLANNED], [
                    'status' => FollowUp::STATUS_BOOKED,
                    'booked_appointment_id' => $appointment->getKey(),
                ], $context);

                return [$appointment, $locked->fresh()];
            });
        } catch (QueryException $e) {
            if (str_contains($e->getMessage(), 'uq_appointments_tenant_provider_start')) {
                return Envelope::error(
                    ErrorCodes::CONFLICT,
                    'This provider already has an appointment at the planned time — the follow-up was not booked.',
                    409,
                    request: $request,
                );
            }

            throw $e;
        }

        $this->audit->record(
            'appointment.booked',
            'appointment',
            $appointment->getKey(),
            ['patientId' => $appointment->patient_id, 'providerStaffId' => $appointment->provider_staff_id, 'startsAt' => $appointment->starts_at?->toIso8601String(), 'source' => Appointment::SOURCE_FOLLOW_UP],
            $request,
        );

        $this->audit->record(
            'follow_up.booked',
            'follow_up',
            $followUp->getKey(),
            ['patientId' => $followUp->patient_id, 'encounterId' => $followUp->encounter_id, 'appointmentId' => $appointment->getKey()],
            $request,
        );

        return Envelope::success(data: [
            'followUp' => self::present($followUp),
            'appointment' => [
                'id' => $appointment->getKey(),
                'facilityId' => $appointment->facility_id,
                'patientId' => $appointment->patient_id,
                'providerStaffId' => $appointment->provider_staff_id,
                'appointmentType' => $appointment->appointment_type,
                'startsAt' => $appointment->starts_at?->toIso8601String(),
                'endsAt' => $appointment->ends_at?->toIso8601String(),
                'status' => $appointment->status,
                'source' => $appointment->source,
                'lockVersion' => $appointment->lock_version,
            ],
        ], request: $request);
    }

    /**
     * POST /follow-ups/{followUp}/cancel — a planned or booked follow-up can
     * be cancelled with a captured reason; completed/cancelled are terminal.
     */
    public function cancel(CancelFollowUpRequest $request, FollowUp $followUp): JsonResponse
    {
        AccessCheck::scoped($followUp, write: true);
        $this->guardStatus($followUp, [FollowUp::STATUS_PLANNED, FollowUp::STATUS_BOOKED], 'cancelled');

        $context = TenantContext::current();
        $this->applyTransition($followUp, [FollowUp::STATUS_PLANNED, FollowUp::STATUS_BOOKED], [
            'status' => FollowUp::STATUS_CANCELLED,
            'cancel_reason' => $request->validated('reason'),
        ], $context);

        $this->audit->record(
            'follow_up.cancelled',
            'follow_up',
            $followUp->getKey(),
            ['patientId' => $followUp->patient_id, 'encounterId' => $followUp->encounter_id, 'cancelReason' => $request->validated('reason')],
            $request,
        );

        return Envelope::success(data: self::present($followUp->fresh()), request: $request);
    }

    /**
     * POST /follow-ups/{followUp}/complete — the return visit happened; the
     * plan is completed (a new encounter records the actual visit).
     */
    public function complete(Request $request, FollowUp $followUp): JsonResponse
    {
        AccessCheck::scoped($followUp, write: true);
        $this->guardStatus($followUp, [FollowUp::STATUS_BOOKED], 'completed');

        $context = TenantContext::current();
        $this->applyTransition($followUp, [FollowUp::STATUS_BOOKED], [
            'status' => FollowUp::STATUS_COMPLETED,
        ], $context);

        $this->audit->record(
            'follow_up.completed',
            'follow_up',
            $followUp->getKey(),
            ['patientId' => $followUp->patient_id, 'encounterId' => $followUp->encounter_id, 'appointmentId' => $followUp->booked_appointment_id],
            $request,
        );

        return Envelope::success(data: self::present($followUp->fresh()), request: $request);
    }

    /* ------------------------------------------------------------------ */

    private function guardStatus(FollowUp $followUp, array $expected, string $gerund): void
    {
        if (! in_array($followUp->status, $expected, true)) {
            throw new ApiException(
                ErrorCodes::CONFLICT,
                'This follow-up cannot be '.$gerund.' from its current state ('.$followUp->status.').',
                409,
            );
        }
    }

    /**
     * @param  list<string>  $expectedStatuses
     * @param  array<string, mixed>  $fields
     */
    private function applyTransition(FollowUp $followUp, array $expectedStatuses, array $fields, TenantContext $context): void
    {
        $query = DB::table('follow_ups')
            ->where('id', $followUp->getKey())
            ->where('lock_version', $followUp->lock_version)
            ->whereIn('status', $expectedStatuses);

        $updated = $query->update(array_merge($fields, [
            'lock_version' => $followUp->lock_version + 1,
            'updated_by' => $context->user?->getKey(),
        ]));

        if ($updated !== 1) {
            throw new ApiException(ErrorCodes::CONFLICT, 'This follow-up was concurrently modified; refresh and retry.', 409);
        }
    }

    /**
     * The encounter provider (the clinician planning the visit).
     */
    private function currentProvider(Encounter $encounter, TenantContext $context): Staff
    {
        $staff = $context->user?->staff()
            ->where('tenant_id', $encounter->tenant_id)
            ->where('status', '!=', Staff::STATUS_DEPARTED)
            ->first();

        if ($staff === null || $staff->getKey() !== $encounter->provider_staff_id) {
            throw new ApiException(ErrorCodes::SCOPE_DENIED, 'Only the encounter provider can plan follow-ups for this visit.', 403);
        }

        return $staff;
    }

    /**
     * @return array<string, mixed>
     */
    private static function present(FollowUp $followUp): array
    {
        return [
            'id' => $followUp->getKey(),
            'patientId' => $followUp->patient_id,
            'encounterId' => $followUp->encounter_id,
            'providerStaffId' => $followUp->provider_staff_id,
            'followUpType' => $followUp->follow_up_type,
            'plannedAt' => $followUp->planned_at?->toIso8601String(),
            'reason' => $followUp->reason,
            'bookedAppointmentId' => $followUp->booked_appointment_id,
            'status' => $followUp->status,
            'cancelReason' => $followUp->cancel_reason,
            'lockVersion' => $followUp->lock_version,
        ];
    }
}
